version: '3'
services:
        app:
                build:
                        context: .
                ports:
                        - 9080:80
                volumes:
                        - .:/var/www/html
